# Generated by Django 3.2.3 on 2021-06-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_size_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
